config/routes.rb
RestPrev::Application.routes.draw do
  get "api/show"

  resources :interfaces



  root :to => 'interfaces#index'

  match "/api/*url" => "api#show", :format => :json

end

app/models/interface.rb
# -*- encoding: utf-8 -*- 
class Interface < ActiveRecord::Base
  attr_accessible :method, :params, :returns, :url, :auth, :title, :status

  def returns_to_hash
    Interface.send(:parse_str_to_hash, self.returns)
  end
  
  def auth_value
    (auth == true) ? "是"  : "否"
  end

  before_save :change_to_json
  def change_to_json
    #str = self.returns
    #self.returns = str.gsub(/"/, "\\"") #.gsub(/\r/,'').gsub(/\//,'') if str
  end

  class << self
    def fetch_result(*args)
      url    = args.first.split("?").first
      method = args.last
      result = Interface.where(:url => url, :method => method).first
      if result
        parse_str_to_hash(result.returns)
      else
        {:result => "No map route"}
      end
    end

    def fetch_result_and_status(*args)
      url    = args.first.split("?").first
      method = args.last
      result = Interface.where(:url => url, :method => method).first
      if result
        [parse_str_to_hash(result.returns), result.status.to_i ]
      else
        [{:result => "No map route"}, 503]
      end
    end

    def select_methods_tag
      [
        ['GET', 'get'],
        ['POST', 'post'],
        ['PUT', 'put'],
        ['DELETE', 'delete']
      ]
    end


    private
    def parse_str_to_hash(str)
      begin 
        JSON.parse str.gsub(/\r/,'').gsub(/\n/,'')#.gsub(/\//,'')
      rescue Excepiton => e
        Rails.logger.info("error message: #{e}")
      ensure
        {:result => "json parse error!"}
      end
    end
  end

end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def show
    #reply = {
    #  :result => "ok"
    #}
    url = request.original_fullpath 
    method = if request.delete?
               "delete"
             elsif request.post?
               "post"
             elsif request.put?
               "put"
             else
               "get"
             end

    reply, status = Interface.fetch_result_and_status(url, method)
    render :json => reply.to_json, :status => status
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :init_interfaces

  def init_interfaces
    @inters = Interface.all
  end

end

app/controllers/interfaces_controller.rb
# -*- encoding: utf-8 -*-
class InterfacesController < ApplicationController

  def index
    @interfaces = Interface.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @interfaces }
    end
  end

  def show
    @interface = Interface.find(params[:id])
    drop_breadcrumb("接口", interfaces_path)
    drop_breadcrumb("<span class='label label-important'>#{@interface.method.upcase}</span>")
    drop_breadcrumb(@interface.title)
  
    respond_to do |format|
      format.html {
      }
      format.json { 
      }
    end
  end

  # GET /interfaces/new
  # GET /interfaces/new.json
  def new
    @interface = Interface.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @interface }
    end
  end

  # GET /interfaces/1/edit
  def edit
    @interface = Interface.find(params[:id])
  end

  # POST /interfaces
  # POST /interfaces.json
  def create
    @interface = Interface.new(params[:interface])

    respond_to do |format|
      if @interface.save
        format.html { redirect_to interface_path(@interface) , notice: '保存成功.' }
        format.json { render json: @interface, status: :created, location: @interface }
      else
        format.html { render action: "new" }
        format.json { render json: @interface.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /interfaces/1
  # PUT /interfaces/1.json
  def update
    @interface = Interface.find(params[:id])

    respond_to do |format|
      if @interface.update_attributes(params[:interface])
        format.html { redirect_to @interface, notice: '接口成功修改.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @interface.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interfaces/1
  # DELETE /interfaces/1.json
  def destroy
    @interface = Interface.find(params[:id])
    @interface.destroy

    respond_to do |format|
      format.html { redirect_to interfaces_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interfaces_helper.rb
# -*- encoding: utf-8 -*- 
module InterfacesHelper
end

module BootstrapHelper
  module Helper

    def notice_message
      flash_messages = []
      flash.each do |type, message|
        type = :success if type == :notice
        text = content_tag(:div, link_to("x", "#", :class => "close", "data-dismiss" => "alert") + message, :class => "alert fade in alert-#{type}")
        flash_messages << text if message
      end
      flash_messages.join("\n").html_safe
    end

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/interfaces/_form.html.erb
<%= form_for @interface, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field large' %>
      <span class="help_inline">
        接口名称，最好使用中文
      </span>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field large' %>
      <span class="help_inline">
        eg: /api/test/interface.json
      </span>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :method, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :method, Interface.select_methods_tag %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :params, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :params, :class => 'text_field' %>
      <span class="help_inline">
        eg: id=1&amp;params1=value1&amp;params2=value2
      </span>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :auth, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :auth, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :returns, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :returns,  :rows => 8 %>
      <span class="help-inline">
        标准的JSON格式:  {  "key": "value"  }
      </span>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "提交", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      interfaces_path, :class => 'btn' %>
    </div>
  <% end %>

app/views/interfaces/edit.html.erb
<h3>修改接口</h3>
<%= render :partial => 'form' %>

app/views/interfaces/index.html.erb
  <h3>简单介绍</h3>
  <blockquote>
    <p class="well well-small">
      提高手机客户端的开发效率，简单高效的生成测试API接口
    <small>chucai</small>
    </p>
  </blockquote>

  <hr/>

app/views/interfaces/new.html.erb
<h3>新建接口</h3>
<%= render :partial => 'form' %>

app/views/interfaces/show.html.erb
<%- model_class = @interface.class -%>
<%= render_breadcrumb %>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @interface.title || "没有名称" %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @interface.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:method) %>:</strong></dt>
  <dd><%= @interface.method.upcase %></dd>
  <dt><strong><%= model_class.human_attribute_name(:params) %>:</strong></dt>
  <dd><%= @interface.params %></dd>
  <dt><strong><%= model_class.human_attribute_name(:auth) %>:</strong></dt>
  <dd><%= @interface.auth_value %></dd>
  <dt><strong>支持格式</strong></dt>
  <dd>JSON</dd>
  <dt><strong>状态码</strong></dt>
  <dd><%= @interface.status %></dd>
  <dt>
    <strong><%= model_class.human_attribute_name(:returns) %>:</strong>
  </dt>
  <dd>
    <pre class="prettyprint nowrap" ref="response-json">
      <%#= @interface.returns_to_hash.to_json %>
      <%= @interface.returns %>
    </pre>
  </dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              interfaces_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_interface_path(@interface), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              interface_path(@interface),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RestPrev" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="/assets/rails.png" rel="shortcut icon">
    <style type="text/css">
      body { padding: 100px 0 0 0; }
    </style>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <h1>
            <%= link_to "InterFace", root_url, :class => "brand" %>
          </h1>

          <div class="span2 pull-right">
            <%= link_to "新建接口",  new_interface_path,  :class => 'btn btn-primary btn-block btn-large' %>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <%= notice_message %>
        <div class="row">
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>
                接口列表
              </h3>
              <ul class="nav nav-list">
                <% for inter in @inters -%>
                  <li class="over-hiden">
                  <a href="<%= interface_path(inter) %>">
                    <span class="label label-important">
                      <%= inter.method.upcase %>
                    </span>
                    &nbsp;
                    <strong>
                      <%= inter.url %>
                    </strong>
                  </a>
                  </li>
                <% end -%>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
          <div class="span9">
            <%= yield %>
          </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
      <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/welcome/index.html.erb
<%= link_to "增加", new_interface_path %>